# Pokemon Name Normalization Dictionary
# Maps various spellings, forms, and common variations to canonical names

pokemon_names = {
    # Generation 1 - Kanto Region
    "bulbasaur": "Bulbasaur",
    "ivysaur": "Ivysaur",
    "venusaur": "Venusaur",
    "charmander": "Charmander",
    "charmeleon": "Charmeleon",
    "charizard": "Charizard",
    "squirtle": "Squirtle",
    "wartortle": "Wartortle",
    "blastoise": "Blastoise",
    "caterpie": "Caterpie",
    "metapod": "Metapod",
    "butterfree": "Butterfree",
    "weedle": "Weedle",
    "kakuna": "Kakuna",
    "beedrill": "Beedrill",
    "pidgey": "Pidgey",
    "pidgeotto": "Pidgeotto",
    "pidgeot": "Pidgeot",
    "rattata": "Rattata",
    "raticate": "Raticate",
    "spearow": "Spearow",
    "fearow": "Fearow",
    "ekans": "Ekans",
    "arbok": "Arbok",
    "pikachu": "Pikachu",
    "raichu": "Raichu",
    "sandshrew": "Sandshrew",
    "sandslash": "Sandslash",
    "nidoran♀": "Nidoran♀",
    "nidoran♂": "Nidoran♂",
    "nidoran-f": "Nidoran♀",
    "nidoran-m": "Nidoran♂",
    "nidoranf": "Nidoran♀",
    "nidoranm": "Nidoran♂",
    "nidoran female": "Nidoran♀",
    "nidoran male": "Nidoran♂",
    "nidorina": "Nidorina",
    "nidoqueen": "Nidoqueen",
    "nidorino": "Nidorino",
    "nidoking": "Nidoking",
    "clefairy": "Clefairy",
    "clefable": "Clefable",
    "vulpix": "Vulpix",
    "ninetales": "Ninetales",
    "jigglypuff": "Jigglypuff",
    "wigglytuff": "Wigglytuff",
    "zubat": "Zubat",
    "golbat": "Golbat",
    "oddish": "Oddish",
    "gloom": "Gloom",
    "vileplume": "Vileplume",
    "paras": "Paras",
    "parasect": "Parasect",
    "venonat": "Venonat",
    "venomoth": "Venomoth",
    "diglett": "Diglett",
    "dugtrio": "Dugtrio",
    "meowth": "Meowth",
    "persian": "Persian",
    "psyduck": "Psyduck",
    "golduck": "Golduck",
    "mankey": "Mankey",
    "primeape": "Primeape",
    "growlithe": "Growlithe",
    "arcanine": "Arcanine",
    "poliwag": "Poliwag",
    "poliwhirl": "Poliwhirl",
    "poliwrath": "Poliwrath",
    "abra": "Abra",
    "kadabra": "Kadabra",
    "alakazam": "Alakazam",
    "machop": "Machop",
    "machoke": "Machoke",
    "machamp": "Machamp",
    "bellsprout": "Bellsprout",
    "weepinbell": "Weepinbell",
    "victreebel": "Victreebel",
    "tentacool": "Tentacool",
    "tentacruel": "Tentacruel",
    "geodude": "Geodude",
    "graveler": "Graveler",
    "golem": "Golem",
    "ponyta": "Ponyta",
    "rapidash": "Rapidash",
    "slowpoke": "Slowpoke",
    "slowbro": "Slowbro",
    "magnemite": "Magnemite",
    "magneton": "Magneton",
    "farfetch'd": "Farfetch'd",
    "farfetchd": "Farfetch'd",
    "farfetched": "Farfetch'd",
    "far fetch'd": "Farfetch'd",
    "doduo": "Doduo",
    "dodrio": "Dodrio",
    "seel": "Seel",
    "dewgong": "Dewgong",
    "grimer": "Grimer",
    "muk": "Muk",
    "shellder": "Shellder",
    "cloyster": "Cloyster",
    "gastly": "Gastly",
    "haunter": "Haunter",
    "gengar": "Gengar",
    "onix": "Onix",
    "drowzee": "Drowzee",
    "hypno": "Hypno",
    "krabby": "Krabby",
    "kingler": "Kingler",
    "voltorb": "Voltorb",
    "electrode": "Electrode",
    "exeggcute": "Exeggcute",
    "exeggutor": "Exeggutor",
    "cubone": "Cubone",
    "marowak": "Marowak",
    "hitmonlee": "Hitmonlee",
    "hitmonchan": "Hitmonchan",
    "lickitung": "Lickitung",
    "koffing": "Koffing",
    "weezing": "Weezing",
    "rhyhorn": "Rhyhorn",
    "rhydon": "Rhydon",
    "chansey": "Chansey",
    "tangela": "Tangela",
    "kangaskhan": "Kangaskhan",
    "horsea": "Horsea",
    "seadra": "Seadra",
    "goldeen": "Goldeen",
    "seaking": "Seaking",
    "staryu": "Staryu",
    "starmie": "Starmie",
    "mr. mime": "Mr. Mime",
    "mr mime": "Mr. Mime",
    "mrmime": "Mr. Mime",
    "mr.mime": "Mr. Mime",
    "scyther": "Scyther",
    "jynx": "Jynx",
    "electabuzz": "Electabuzz",
    "magmar": "Magmar",
    "pinsir": "Pinsir",
    "tauros": "Tauros",
    "magikarp": "Magikarp",
    "gyarados": "Gyarados",
    "lapras": "Lapras",
    "ditto": "Ditto",
    "eevee": "Eevee",
    "vaporeon": "Vaporeon",
    "jolteon": "Jolteon",
    "flareon": "Flareon",
    "porygon": "Porygon",
    "omanyte": "Omanyte",
    "omastar": "Omastar",
    "kabuto": "Kabuto",
    "kabutops": "Kabutops",
    "aerodactyl": "Aerodactyl",
    "snorlax": "Snorlax",
    "articuno": "Articuno",
    "zapdos": "Zapdos",
    "moltres": "Moltres",
    "dratini": "Dratini",
    "dragonair": "Dragonair",
    "dragonite": "Dragonite",
    "mewtwo": "Mewtwo",
    "mew": "Mew",
    # Generation 2 - Johto Region
    "chikorita": "Chikorita",
    "bayleef": "Bayleef",
    "meganium": "Meganium",
    "cyndaquil": "Cyndaquil",
    "quilava": "Quilava",
    "typhlosion": "Typhlosion",
    "totodile": "Totodile",
    "croconaw": "Croconaw",
    "feraligatr": "Feraligatr",
    "sentret": "Sentret",
    "furret": "Furret",
    "hoothoot": "Hoothoot",
    "noctowl": "Noctowl",
    "ledyba": "Ledyba",
    "ledian": "Ledian",
    "spinarak": "Spinarak",
    "ariados": "Ariados",
    "crobat": "Crobat",
    "chinchou": "Chinchou",
    "lanturn": "Lanturn",
    "pichu": "Pichu",
    "cleffa": "Cleffa",
    "igglybuff": "Igglybuff",
    "togepi": "Togepi",
    "togetic": "Togetic",
    "natu": "Natu",
    "xatu": "Xatu",
    "mareep": "Mareep",
    "flaaffy": "Flaaffy",
    "ampharos": "Ampharos",
    "bellossom": "Bellossom",
    "marill": "Marill",
    "azumarill": "Azumarill",
    "sudowoodo": "Sudowoodo",
    "politoed": "Politoed",
    "hoppip": "Hoppip",
    "skiploom": "Skiploom",
    "jumpluff": "Jumpluff",
    "aipom": "Aipom",
    "sunkern": "Sunkern",
    "sunflora": "Sunflora",
    "yanma": "Yanma",
    "wooper": "Wooper",
    "quagsire": "Quagsire",
    "espeon": "Espeon",
    "umbreon": "Umbreon",
    "murkrow": "Murkrow",
    "slowking": "Slowking",
    "misdreavus": "Misdreavus",
    "unown": "Unown",
    "wobbuffet": "Wobbuffet",
    "girafarig": "Girafarig",
    "pineco": "Pineco",
    "forretress": "Forretress",
    "dunsparce": "Dunsparce",
    "gligar": "Gligar",
    "steelix": "Steelix",
    "snubbull": "Snubbull",
    "granbull": "Granbull",
    "qwilfish": "Qwilfish",
    "scizor": "Scizor",
    "shuckle": "Shuckle",
    "heracross": "Heracross",
    "sneasel": "Sneasel",
    "teddiursa": "Teddiursa",
    "ursaring": "Ursaring",
    "slugma": "Slugma",
    "magcargo": "Magcargo",
    "swinub": "Swinub",
    "piloswine": "Piloswine",
    "corsola": "Corsola",
    "remoraid": "Remoraid",
    "octillery": "Octillery",
    "delibird": "Delibird",
    "mantine": "Mantine",
    "skarmory": "Skarmory",
    "houndour": "Houndour",
    "houndoom": "Houndoom",
    "kingdra": "Kingdra",
    "phanpy": "Phanpy",
    "donphan": "Donphan",
    "porygon2": "Porygon2",
    "stantler": "Stantler",
    "smeargle": "Smeargle",
    "tyrogue": "Tyrogue",
    "hitmontop": "Hitmontop",
    "smoochum": "Smoochum",
    "elekid": "Elekid",
    "magby": "Magby",
    "miltank": "Miltank",
    "blissey": "Blissey",
    "raikou": "Raikou",
    "entei": "Entei",
    "suicune": "Suicune",
    "larvitar": "Larvitar",
    "pupitar": "Pupitar",
    "tyranitar": "Tyranitar",
    "lugia": "Lugia",
    "ho-oh": "Ho-Oh",
    "ho oh": "Ho-Oh",
    "hooh": "Ho-Oh",
    "celebi": "Celebi",
    # Generation 3 - Hoenn Region
    "treecko": "Treecko",
    "grovyle": "Grovyle",
    "sceptile": "Sceptile",
    "torchic": "Torchic",
    "combusken": "Combusken",
    "blaziken": "Blaziken",
    "mudkip": "Mudkip",
    "marshtomp": "Marshtomp",
    "swampert": "Swampert",
    "poochyena": "Poochyena",
    "mightyena": "Mightyena",
    "zigzagoon": "Zigzagoon",
    "linoone": "Linoone",
    "wurmple": "Wurmple",
    "silcoon": "Silcoon",
    "beautifly": "Beautifly",
    "cascoon": "Cascoon",
    "dustox": "Dustox",
    "lotad": "Lotad",
    "lombre": "Lombre",
    "ludicolo": "Ludicolo",
    "seedot": "Seedot",
    "nuzleaf": "Nuzleaf",
    "shiftry": "Shiftry",
    "taillow": "Taillow",
    "swellow": "Swellow",
    "wingull": "Wingull",
    "pelipper": "Pelipper",
    "ralts": "Ralts",
    "kirlia": "Kirlia",
    "gardevoir": "Gardevoir",
    "surskit": "Surskit",
    "masquerain": "Masquerain",
    "shroomish": "Shroomish",
    "breloom": "Breloom",
    "slakoth": "Slakoth",
    "vigoroth": "Vigoroth",
    "slaking": "Slaking",
    "nincada": "Nincada",
    "ninjask": "Ninjask",
    "shedinja": "Shedinja",
    "whismur": "Whismur",
    "loudred": "Loudred",
    "exploud": "Exploud",
    "makuhita": "Makuhita",
    "hariyama": "Hariyama",
    "azurill": "Azurill",
    "nosepass": "Nosepass",
    "skitty": "Skitty",
    "delcatty": "Delcatty",
    "sableye": "Sableye",
    "mawile": "Mawile",
    "aron": "Aron",
    "lairon": "Lairon",
    "aggron": "Aggron",
    "meditite": "Meditite",
    "medicham": "Medicham",
    "electrike": "Electrike",
    "manectric": "Manectric",
    "plusle": "Plusle",
    "minun": "Minun",
    "volbeat": "Volbeat",
    "illumise": "Illumise",
    "roselia": "Roselia",
    "gulpin": "Gulpin",
    "swalot": "Swalot",
    "carvanha": "Carvanha",
    "sharpedo": "Sharpedo",
    "wailmer": "Wailmer",
    "wailord": "Wailord",
    "numel": "Numel",
    "camerupt": "Camerupt",
    "torkoal": "Torkoal",
    "spoink": "Spoink",
    "grumpig": "Grumpig",
    "spinda": "Spinda",
    "trapinch": "Trapinch",
    "vibrava": "Vibrava",
    "flygon": "Flygon",
    "cacnea": "Cacnea",
    "cacturne": "Cacturne",
    "swablu": "Swablu",
    "altaria": "Altaria",
    "zangoose": "Zangoose",
    "seviper": "Seviper",
    "lunatone": "Lunatone",
    "solrock": "Solrock",
    "barboach": "Barboach",
    "whiscash": "Whiscash",
    "corphish": "Corphish",
    "crawdaunt": "Crawdaunt",
    "baltoy": "Baltoy",
    "claydol": "Claydol",
    "lileep": "Lileep",
    "cradily": "Cradily",
    "anorith": "Anorith",
    "armaldo": "Armaldo",
    "feebas": "Feebas",
    "milotic": "Milotic",
    "castform": "Castform",
    "kecleon": "Kecleon",
    "shuppet": "Shuppet",
    "banette": "Banette",
    "duskull": "Duskull",
    "dusclops": "Dusclops",
    "tropius": "Tropius",
    "chimecho": "Chimecho",
    "absol": "Absol",
    "wynaut": "Wynaut",
    "snorunt": "Snorunt",
    "glalie": "Glalie",
    "spheal": "Spheal",
    "sealeo": "Sealeo",
    "walrein": "Walrein",
    "clamperl": "Clamperl",
    "huntail": "Huntail",
    "gorebyss": "Gorebyss",
    "relicanth": "Relicanth",
    "luvdisc": "Luvdisc",
    "bagon": "Bagon",
    "shelgon": "Shelgon",
    "salamence": "Salamence",
    "beldum": "Beldum",
    "metang": "Metang",
    "metagross": "Metagross",
    "regirock": "Regirock",
    "regice": "Regice",
    "registeel": "Registeel",
    "latias": "Latias",
    "latios": "Latios",
    "kyogre": "Kyogre",
    "groudon": "Groudon",
    "rayquaza": "Rayquaza",
    "jirachi": "Jirachi",
    "deoxys": "Deoxys",
    # Generation 4 - Sinnoh Region
    "turtwig": "Turtwig",
    "grotle": "Grotle",
    "torterra": "Torterra",
    "chimchar": "Chimchar",
    "monferno": "Monferno",
    "infernape": "Infernape",
    "piplup": "Piplup",
    "prinplup": "Prinplup",
    "empoleon": "Empoleon",
    "starly": "Starly",
    "staravia": "Staravia",
    "staraptor": "Staraptor",
    "bidoof": "Bidoof",
    "bibarel": "Bibarel",
    "kricketot": "Kricketot",
    "kricketune": "Kricketune",
    "shinx": "Shinx",
    "luxio": "Luxio",
    "luxray": "Luxray",
    "budew": "Budew",
    "roserade": "Roserade",
    "cranidos": "Cranidos",
    "rampardos": "Rampardos",
    "shieldon": "Shieldon",
    "bastiodon": "Bastiodon",
    "burmy": "Burmy",
    "wormadam": "Wormadam",
    "mothim": "Mothim",
    "combee": "Combee",
    "vespiquen": "Vespiquen",
    "pachirisu": "Pachirisu",
    "buizel": "Buizel",
    "floatzel": "Floatzel",
    "cherubi": "Cherubi",
    "cherrim": "Cherrim",
    "shellos": "Shellos",
    "gastrodon": "Gastrodon",
    "ambipom": "Ambipom",
    "drifloon": "Drifloon",
    "drifblim": "Drifblim",
    "buneary": "Buneary",
    "lopunny": "Lopunny",
    "mismagius": "Mismagius",
    "honchkrow": "Honchkrow",
    "glameow": "Glameow",
    "purugly": "Purugly",
    "chingling": "Chingling",
    "stunky": "Stunky",
    "skuntank": "Skuntank",
    "bronzor": "Bronzor",
    "bronzong": "Bronzong",
    "bonsly": "Bonsly",
    "mime jr.": "Mime Jr.",
    "mime jr": "Mime Jr.",
    "mimejr": "Mime Jr.",
    "mime junior": "Mime Jr.",
    "happiny": "Happiny",
    "chatot": "Chatot",
    "spiritomb": "Spiritomb",
    "gible": "Gible",
    "gabite": "Gabite",
    "garchomp": "Garchomp",
    "munchlax": "Munchlax",
    "riolu": "Riolu",
    "lucario": "Lucario",
    "hippopotas": "Hippopotas",
    "hippowdon": "Hippowdon",
    "skorupi": "Skorupi",
    "drapion": "Drapion",
    "croagunk": "Croagunk",
    "toxicroak": "Toxicroak",
    "carnivine": "Carnivine",
    "finneon": "Finneon",
    "lumineon": "Lumineon",
    "mantyke": "Mantyke",
    "snover": "Snover",
    "abomasnow": "Abomasnow",
    "weavile": "Weavile",
    "magnezone": "Magnezone",
    "lickilicky": "Lickilicky",
    "rhyperior": "Rhyperior",
    "tangrowth": "Tangrowth",
    "electivire": "Electivire",
    "magmortar": "Magmortar",
    "togekiss": "Togekiss",
    "yanmega": "Yanmega",
    "leafeon": "Leafeon",
    "glaceon": "Glaceon",
    "gliscor": "Gliscor",
    "mamoswine": "Mamoswine",
    "porygon-z": "Porygon-Z",
    "porygonz": "Porygon-Z",
    "porygon z": "Porygon-Z",
    "gallade": "Gallade",
    "probopass": "Probopass",
    "dusknoir": "Dusknoir",
    "froslass": "Froslass",
    "rotom": "Rotom",
    "uxie": "Uxie",
    "mesprit": "Mesprit",
    "azelf": "Azelf",
    "dialga": "Dialga",
    "palkia": "Palkia",
    "heatran": "Heatran",
    "regigigas": "Regigigas",
    "giratina": "Giratina",
    "cresselia": "Cresselia",
    "phione": "Phione",
    "manaphy": "Manaphy",
    "darkrai": "Darkrai",
    "shaymin": "Shaymin",
    "arceus": "Arceus",
    # Generation 5 - Unova Region
    "victini": "Victini",
    "snivy": "Snivy",
    "servine": "Servine",
    "serperior": "Serperior",
    "tepig": "Tepig",
    "pignite": "Pignite",
    "emboar": "Emboar",
    "oshawott": "Oshawott",
    "dewott": "Dewott",
    "samurott": "Samurott",
    "patrat": "Patrat",
    "watchog": "Watchog",
    "lillipup": "Lillipup",
    "herdier": "Herdier",
    "stoutland": "Stoutland",
    "purrloin": "Purrloin",
    "liepard": "Liepard",
    "pansage": "Pansage",
    "simisage": "Simisage",
    "pansear": "Pansear",
    "simisear": "Simisear",
    "panpour": "Panpour",
    "simipour": "Simipour",
    "munna": "Munna",
    "musharna": "Musharna",
    "pidove": "Pidove",
    "tranquill": "Tranquill",
    "unfezant": "Unfezant",
    "blitzle": "Blitzle",
    "zebstrika": "Zebstrika",
    "roggenrola": "Roggenrola",
    "boldore": "Boldore",
    "gigalith": "Gigalith",
    "woobat": "Woobat",
    "swoobat": "Swoobat",
    "drilbur": "Drilbur",
    "excadrill": "Excadrill",
    "audino": "Audino",
    "timburr": "Timburr",
    "gurdurr": "Gurdurr",
    "conkeldurr": "Conkeldurr",
    "tympole": "Tympole",
    "palpitoad": "Palpitoad",
    "seismitoad": "Seismitoad",
    "throh": "Throh",
    "sawk": "Sawk",
    "sewaddle": "Sewaddle",
    "swadloon": "Swadloon",
    "leavanny": "Leavanny",
    "venipede": "Venipede",
    "whirlipede": "Whirlipede",
    "scolipede": "Scolipede",
    "cottonee": "Cottonee",
    "whimsicott": "Whimsicott",
    "petilil": "Petilil",
    "lilligant": "Lilligant",
    "basculin": "Basculin",
    "sandile": "Sandile",
    "krokorok": "Krokorok",
    "krookodile": "Krookodile",
    "darumaka": "Darumaka",
    "darmanitan": "Darmanitan",
    "maractus": "Maractus",
    "dwebble": "Dwebble",
    "crustle": "Crustle",
    "scraggy": "Scraggy",
    "scrafty": "Scrafty",
    "sigilyph": "Sigilyph",
    "yamask": "Yamask",
    "cofagrigus": "Cofagrigus",
    "tirtouga": "Tirtouga",
    "carracosta": "Carracosta",
    "archen": "Archen",
    "archeops": "Archeops",
    "trubbish": "Trubbish",
    "garbodor": "Garbodor",
    "zorua": "Zorua",
    "zoroark": "Zoroark",
    "minccino": "Minccino",
    "cinccino": "Cinccino",
    "gothita": "Gothita",
    "gothorita": "Gothorita",
    "gothitelle": "Gothitelle",
    "solosis": "Solosis",
    "duosion": "Duosion",
    "reuniclus": "Reuniclus",
    "ducklett": "Ducklett",
    "swanna": "Swanna",
    "vanillite": "Vanillite",
    "vanillish": "Vanillish",
    "vanilluxe": "Vanilluxe",
    "deerling": "Deerling",
    "sawsbuck": "Sawsbuck",
    "emolga": "Emolga",
    "karrablast": "Karrablast",
    "escavalier": "Escavalier",
    "foongus": "Foongus",
    "amoonguss": "Amoonguss",
    "frillish": "Frillish",
    "jellicent": "Jellicent",
    "alomomola": "Alomomola",
    "joltik": "Joltik",
    "galvantula": "Galvantula",
    "ferroseed": "Ferroseed",
    "ferrothorn": "Ferrothorn",
    "klink": "Klink",
    "klang": "Klang",
    "klinklang": "Klinklang",
    "tynamo": "Tynamo",
    "eelektrik": "Eelektrik",
    "eelektross": "Eelektross",
    "elgyem": "Elgyem",
    "beheeyem": "Beheeyem",
    "litwick": "Litwick",
    "lampent": "Lampent",
    "chandelure": "Chandelure",
    "axew": "Axew",
    "fraxure": "Fraxure",
    "haxorus": "Haxorus",
    "cubchoo": "Cubchoo",
    "beartic": "Beartic",
    "cryogonal": "Cryogonal",
    "shelmet": "Shelmet",
    "accelgor": "Accelgor",
    "stunfisk": "Stunfisk",
    "mienfoo": "Mienfoo",
    "mienshao": "Mienshao",
    "druddigon": "Druddigon",
    "golett": "Golett",
    "golurk": "Golurk",
    "pawniard": "Pawniard",
    "bisharp": "Bisharp",
    "bouffalant": "Bouffalant",
    "rufflet": "Rufflet",
    "braviary": "Braviary",
    "vullaby": "Vullaby",
    "mandibuzz": "Mandibuzz",
    "heatmor": "Heatmor",
    "durant": "Durant",
    "deino": "Deino",
    "zweilous": "Zweilous",
    "hydreigon": "Hydreigon",
    "larvesta": "Larvesta",
    "volcarona": "Volcarona",
    "cobalion": "Cobalion",
    "terrakion": "Terrakion",
    "virizion": "Virizion",
    "tornadus": "Tornadus",
    "thundurus": "Thundurus",
    "reshiram": "Reshiram",
    "zekrom": "Zekrom",
    "landorus": "Landorus",
    "kyurem": "Kyurem",
    "keldeo": "Keldeo",
    "meloetta": "Meloetta",
    "genesect": "Genesect",
    # Generation 6 - Kalos Region
    "chespin": "Chespin",
    "quilladin": "Quilladin",
    "chesnaught": "Chesnaught",
    "fennekin": "Fennekin",
    "braixen": "Braixen",
    "delphox": "Delphox",
    "froakie": "Froakie",
    "frogadier": "Frogadier",
    "greninja": "Greninja",
    "bunnelby": "Bunnelby",
    "diggersby": "Diggersby",
    "fletchling": "Fletchling",
    "fletchinder": "Fletchinder",
    "talonflame": "Talonflame",
    "scatterbug": "Scatterbug",
    "spewpa": "Spewpa",
    "vivillon": "Vivillon",
    "litleo": "Litleo",
    "pyroar": "Pyroar",
    "flabebe": "Flabébé",
    "floette": "Floette",
    "florges": "Florges",
    "skiddo": "Skiddo",
    "gogoat": "Gogoat",
    "pancham": "Pancham",
    "pangoro": "Pangoro",
    "furfrou": "Furfrou",
    "espurr": "Espurr",
    "meowstic": "Meowstic",
    "honedge": "Honedge",
    "doublade": "Doublade",
    "aegislash": "Aegislash",
    "spritzee": "Spritzee",
    "aromatisse": "Aromatisse",
    "swirlix": "Swirlix",
    "slurpuff": "Slurpuff",
    "inkay": "Inkay",
    "malamar": "Malamar",
    "binacle": "Binacle",
    "barbaracle": "Barbaracle",
    "skrelp": "Skrelp",
    "dragalge": "Dragalge",
    "clauncher": "Clauncher",
    "clawitzer": "Clawitzer",
    "helioptile": "Helioptile",
    "heliolisk": "Heliolisk",
    "tyrunt": "Tyrunt",
    "tyrantrum": "Tyrantrum",
    "amaura": "Amaura",
    "aurorus": "Aurorus",
    "sylveon": "Sylveon",
    "hawlucha": "Hawlucha",
    "dedenne": "Dedenne",
    "carbink": "Carbink",
    "goomy": "Goomy",
    "sliggoo": "Sliggoo",
    "goodra": "Goodra",
    "klefki": "Klefki",
    "phantump": "Phantump",
    "trevenant": "Trevenant",
    "pumpkaboo": "Pumpkaboo",
    "gourgeist": "Gourgeist",
    "bergmite": "Bergmite",
    "avalugg": "Avalugg",
    "noibat": "Noibat",
    "noivern": "Noivern",
    "xerneas": "Xerneas",
    "yveltal": "Yveltal",
    "zygarde": "Zygarde",
    "diancie": "Diancie",
    "hoopa": "Hoopa",
    "volcanion": "Volcanion",
    # Generation 7 - Alola Region
    "rowlet": "Rowlet",
    "dartrix": "Dartrix",
    "decidueye": "Decidueye",
    "litten": "Litten",
    "torracat": "Torracat",
    "incineroar": "Incineroar",
    "popplio": "Popplio",
    "brionne": "Brionne",
    "primarina": "Primarina",
    "pikipek": "Pikipek",
    "trumbeak": "Trumbeak",
    "toucannon": "Toucannon",
    "yungoos": "Yungoos",
    "gumshoos": "Gumshoos",
    "grubbin": "Grubbin",
    "charjabug": "Charjabug",
    "vikavolt": "Vikavolt",
    "crabrawler": "Crabrawler",
    "crabominable": "Crabominable",
    "oricorio": "Oricorio",
    "cutiefly": "Cutiefly",
    "ribombee": "Ribombee",
    "rockruff": "Rockruff",
    "lycanroc": "Lycanroc",
    "wishiwashi": "Wishiwashi",
    "mareanie": "Mareanie",
    "toxapex": "Toxapex",
    "mudbray": "Mudbray",
    "mudsdale": "Mudsdale",
    "dewpider": "Dewpider",
    "araquanid": "Araquanid",
    "fomantis": "Fomantis",
    "lurantis": "Lurantis",
    "morelull": "Morelull",
    "shiinotic": "Shiinotic",
    "salandit": "Salandit",
    "salazzle": "Salazzle",
    "stufful": "Stufful",
    "bewear": "Bewear",
    "bounsweet": "Bounsweet",
    "steenee": "Steenee",
    "tsareena": "Tsareena",
    "comfey": "Comfey",
    "oranguru": "Oranguru",
    "passimian": "Passimian",
    "wimpod": "Wimpod",
    "golisopod": "Golisopod",
    "sandygast": "Sandygast",
    "palossand": "Palossand",
    "pyukumuku": "Pyukumuku",
    "type null": "Type: Null",
    "type: null": "Type: Null",
    "typenull": "Type: Null",
    "silvally": "Silvally",
    "minior": "Minior",
    "komala": "Komala",
    "turtonator": "Turtonator",
    "togedemaru": "Togedemaru",
    "mimikyu": "Mimikyu",
    "bruxish": "Bruxish",
    "drampa": "Drampa",
    "dhelmise": "Dhelmise",
    "jangmo-o": "Jangmo-o",
    "jangmoo": "Jangmo-o",
    "hakamo-o": "Hakamo-o",
    "hakamoo": "Hakamo-o",
    "kommo-o": "Kommo-o",
    "kommoo": "Kommo-o",
    "tapu koko": "Tapu Koko",
    "tapukoko": "Tapu Koko",
    "tapu lele": "Tapu Lele",
    "tapulele": "Tapu Lele",
    "tapu bulu": "Tapu Bulu",
    "tapubulu": "Tapu Bulu",
    "tapu fini": "Tapu Fini",
    "tapufini": "Tapu Fini",
    "cosmog": "Cosmog",
    "cosmoem": "Cosmoem",
    "solgaleo": "Solgaleo",
    "lunala": "Lunala",
    "necrozma": "Necrozma",
    "magearna": "Magearna",
    "marshadow": "Marshadow",
    "poipole": "Poipole",
    "naganadel": "Naganadel",
    "stakataka": "Stakataka",
    "blacephalon": "Blacephalon",
    "zeraora": "Zeraora",
    "meltan": "Meltan",
    "melmetal": "Melmetal",
    # Generation 8 - Galar Region
    "grookey": "Grookey",
    "thwackey": "Thwackey",
    "rillaboom": "Rillaboom",
    "scorbunny": "Scorbunny",
    "raboot": "Raboot",
    "cinderace": "Cinderace",
    "sobble": "Sobble",
    "drizzile": "Drizzile",
    "inteleon": "Inteleon",
    "skwovet": "Skwovet",
    "greedent": "Greedent",
    "rookidee": "Rookidee",
    "corvisquire": "Corvisquire",
    "corviknight": "Corviknight",
    "blipbug": "Blipbug",
    "dottler": "Dottler",
    "orbeetle": "Orbeetle",
    "nickit": "Nickit",
    "thievul": "Thievul",
    "gossifleur": "Gossifleur",
    "eldegoss": "Eldegoss",
    "wooloo": "Wooloo",
    "dubwool": "Dubwool",
    "chewtle": "Chewtle",
    "drednaw": "Drednaw",
    "yamper": "Yamper",
    "boltund": "Boltund",
    "rolycoly": "Rolycoly",
    "carkol": "Carkol",
    "coalossal": "Coalossal",
    "applin": "Applin",
    "flapple": "Flapple",
    "appletun": "Appletun",
    "silicobra": "Silicobra",
    "sandaconda": "Sandaconda",
    "cramorant": "Cramorant",
    "arrokuda": "Arrokuda",
    "barraskewda": "Barraskewda",
    "toxel": "Toxel",
    "toxtricity": "Toxtricity",
    "sizzlipede": "Sizzlipede",
    "centiskorch": "Centiskorch",
    "clobbopus": "Clobbopus",
    "grapploct": "Grapploct",
    "sinistea": "Sinistea",
    "polteageist": "Polteageist",
    "hatenna": "Hatenna",
    "hattrem": "Hattrem",
    "hatterene": "Hatterene",
    "impidimp": "Impidimp",
    "morgrem": "Morgrem",
    "grimmsnarl": "Grimmsnarl",
    "obstagoon": "Obstagoon",
    "perrserker": "Perrserker",
    "cursola": "Cursola",
    "sirfetchd": "Sirfetch'd",
    "sirfetch'd": "Sirfetch'd",
    "mr rime": "Mr. Rime",
    "mr. rime": "Mr. Rime",
    "mrrime": "Mr. Rime",
    "runerigus": "Runerigus",
    "milcery": "Milcery",
    "alcremie": "Alcremie",
    "falinks": "Falinks",
    "pincurchin": "Pincurchin",
    "snom": "Snom",
    "frosmoth": "Frosmoth",
    "stonjourner": "Stonjourner",
    "eiscue": "Eiscue",
    "indeedee": "Indeedee",
    "morpeko": "Morpeko",
    "cufant": "Cufant",
    "copperajah": "Copperajah",
    "dracozolt": "Dracozolt",
    "arctozolt": "Arctozolt",
    "dracovish": "Dracovish",
    "arctovish": "Arctovish",
    "duraludon": "Duraludon",
    "dreepy": "Dreepy",
    "drakloak": "Drakloak",
    "dragapult": "Dragapult",
    "zacian": "Zacian",
    "zamazenta": "Zamazenta",
    "eternatus": "Eternatus",
    "kubfu": "Kubfu",
    "urshifu": "Urshifu",
    "regieleki": "Regieleki",
    "regidrago": "Regidrago",
    "glastrier": "Glastrier",
    "spectrier": "Spectrier",
    "calyrex": "Calyrex",
    # Generation 9 - Paldea Region
    "sprigatito": "Sprigatito",
    "floragato": "Floragato",
    "meowscarada": "Meowscarada",
    "fuecoco": "Fuecoco",
    "crocalor": "Crocalor",
    "skeledirge": "Skeledirge",
    "quaxly": "Quaxly",
    "quaxwell": "Quaxwell",
    "quaquaval": "Quaquaval",
    "lechonk": "Lechonk",
    "oinkologne": "Oinkologne",
    "tarountula": "Tarountula",
    "spidops": "Spidops",
    "nymble": "Nymble",
    "lokix": "Lokix",
    "pawmi": "Pawmi",
    "pawmo": "Pawmo",
    "pawmot": "Pawmot",
    "tandemaus": "Tandemaus",
    "maushold": "Maushold",
    "fidough": "Fidough",
    "dachsbun": "Dachsbun",
    "smoliv": "Smoliv",
    "dolliv": "Dolliv",
    "arboliva": "Arboliva",
    "squawkabilly": "Squawkabilly",
    "nacli": "Nacli",
    "naclstack": "Naclstack",
    "garganacl": "Garganacl",
    "charcadet": "Charcadet",
    "armarouge": "Armarouge",
    "ceruledge": "Ceruledge",
    "tadbulb": "Tadbulb",
    "bellibolt": "Bellibolt",
    "wattrel": "Wattrel",
    "kilowattrel": "Kilowattrel",
    "maschiff": "Maschiff",
    "mabosstiff": "Mabosstiff",
    "shroodle": "Shroodle",
    "grafaiai": "Grafaiai",
    "bramblin": "Bramblin",
    "brambleghast": "Brambleghast",
    "toedscool": "Toedscool",
    "toedscruel": "Toedscruel",
    "klawf": "Klawf",
    "capsakid": "Capsakid",
    "scovillain": "Scovillain",
    "rellor": "Rellor",
    "rabsca": "Rabsca",
    "flittle": "Flittle",
    "espathra": "Espathra",
    "tinkatink": "Tinkatink",
    "tinkaton": "Tinkaton",
    "wiglett": "Wiglett",
    "wugtrio": "Wugtrio",
    "bombirdier": "Bombirdier",
    "finizen": "Finizen",
    "palafin": "Palafin",
    "varoom": "Varoom",
    "revavroom": "Revavroom",
    "cyclizar": "Cyclizar",
    "orthworm": "Orthworm",
    "glimmet": "Glimmet",
    "glimmora": "Glimmora",
    "greavard": "Greavard",
    "houndstone": "Houndstone",
    "flamigo": "Flamigo",
    "cetoddle": "Cetoddle",
    "cetitan": "Cetitan",
    "veluza": "Veluza",
    "dondozo": "Dondozo",
    "tatsugiri": "Tatsugiri",
    "annihilape": "Annihilape",
    "clodsire": "Clodsire",
    "farigiraf": "Farigiraf",
    "dudunsparce": "Dudunsparce",
    "kingambit": "Kingambit",
    "great tusk": "Great Tusk",
    "greattusk": "Great Tusk",
    "scream tail": "Scream Tail",
    "screamtail": "Scream Tail",
    "brute bonnet": "Brute Bonnet",
    "brutebonnet": "Brute Bonnet",
    "flutter mane": "Flutter Mane",
    "fluttermane": "Flutter Mane",
    "slither wing": "Slither Wing",
    "slitherwing": "Slither Wing",
    "sandy shocks": "Sandy Shocks",
    "sandyshocks": "Sandy Shocks",
    "iron treads": "Iron Treads",
    "irontreads": "Iron Treads",
    "iron bundle": "Iron Bundle",
    "ironbundle": "Iron Bundle",
    "iron hands": "Iron Hands",
    "ironhands": "Iron Hands",
    "iron jugulis": "Iron Jugulis",
    "ironjugulis": "Iron Jugulis",
    "iron moth": "Iron Moth",
    "ironmoth": "Iron Moth",
    "iron thorns": "Iron Thorns",
    "ironthorns": "Iron Thorns",
    "frigibax": "Frigibax",
    "arctibax": "Arctibax",
    "baxcalibur": "Baxcalibur",
    "gimmighoul": "Gimmighoul",
    "gholdengo": "Gholdengo",
    "wo-chien": "Wo-Chien",
    "wochien": "Wo-Chien",
    "chien-pao": "Chien-Pao",
    "chienpao": "Chien-Pao",
    "ting-lu": "Ting-Lu",
    "tinglu": "Ting-Lu",
    "chi-yu": "Chi-Yu",
    "chiyu": "Chi-Yu",
    "roaring moon": "Roaring Moon",
    "roaringmoon": "Roaring Moon",
    "iron valiant": "Iron Valiant",
    "ironvaliant": "Iron Valiant",
    "koraidon": "Koraidon",
    "miraidon": "Miraidon",
    "walking wake": "Walking Wake",
    "walkingwake": "Walking Wake",
    "iron leaves": "Iron Leaves",
    "ironleaves": "Iron Leaves",
    "dipplin": "Dipplin",
    "poltchageist": "Poltchageist",
    "sinistcha": "Sinistcha",
    "okidogi": "Okidogi",
    "munkidori": "Munkidori",
    "fezandipiti": "Fezandipiti",
    "ogerpon": "Ogerpon",
    "archaludon": "Archaludon",
    "hydrapple": "Hydrapple",
    "gouging fire": "Gouging Fire",
    "gougingfire": "Gouging Fire",
    "raging bolt": "Raging Bolt",
    "ragingbolt": "Raging Bolt",
    "iron boulder": "Iron Boulder",
    "ironboulder": "Iron Boulder",
    "iron crown": "Iron Crown",
    "ironcrown": "Iron Crown",
    "terapagos": "Terapagos",
    "pecharunt": "Pecharunt",
}

set_names = {  # Sword & Shield Base Set
    "sword shield": "Sword & Shield Base",
    "sword and shield base": "Sword & Shield Base",
    "sword & shield": "Sword & Shield Base",
    "swsh": "Sword & Shield Base",
    "swsh1": "Sword & Shield Base",
    "swsh base": "Sword & Shield Base",
    "ssh": "Sword & Shield Base",
    "base sword shield": "Sword & Shield Base",
    # Sword & Shield Promo
    "sword shield promo": "Sword & Shield Base Promo",
    "sword and shield base promo": "Sword & Shield Base Promo",
    "sword & shield promo": "Sword & Shield Base Promo",
    "swsh promo": "Sword & Shield Base Promo",
    "swsh1 promo": "Sword & Shield Base Promo",
    "swsh base promo": "Sword & Shield Base Promo",
    "ssh promo": "Sword & Shield Base Promo",
    "base sword shield promo": "Sword & Shield Promo",
    # Rebel Clash
    "rebel clash": "Rebel Clash",
    "swsh2": "Rebel Clash",
    "swsh02": "Rebel Clash",
    "rebel": "Rebel Clash",
    # Darkness Ablaze
    "darkness ablaze": "Darkness Ablaze",
    "swsh3": "Darkness Ablaze",
    "swsh03": "Darkness Ablaze",
    "darkness": "Darkness Ablaze",
    "ablaze": "Darkness Ablaze",
    # Vivid Voltage
    "vivid voltage": "Vivid Voltage",
    "swsh4": "Vivid Voltage",
    "swsh04": "Vivid Voltage",
    "vivid": "Vivid Voltage",
    "voltage": "Vivid Voltage",
    # Battle Styles
    "battle styles": "Battle Styles",
    "swsh5": "Battle Styles",
    "swsh05": "Battle Styles",
    "battle": "Battle Styles",
    "styles": "Battle Styles",
    # Chilling Reign
    "chilling reign": "Chilling Reign",
    "swsh6": "Chilling Reign",
    "swsh06": "Chilling Reign",
    "chilling": "Chilling Reign",
    "reign": "Chilling Reign",
    # Evolving Skies
    "evolving skies": "Evolving Skies",
    "swsh7": "Evolving Skies",
    "swsh07": "Evolving Skies",
    "evolving": "Evolving Skies",
    "skies": "Evolving Skies",
    "evo skies": "Evolving Skies",
    # Fusion Strike
    "fusion strike": "Fusion Strike",
    "swsh8": "Fusion Strike",
    "swsh08": "Fusion Strike",
    "fusion": "Fusion Strike",
    "strike": "Fusion Strike",
    # Brilliant Stars
    "brilliant stars": "Brilliant Stars",
    "swsh9": "Brilliant Stars",
    "swsh09": "Brilliant Stars",
    "brilliant": "Brilliant Stars",
    "stars": "Brilliant Stars",
    # Astral Radiance
    "astral radiance": "Astral Radiance",
    "swsh10": "Astral Radiance",
    "astral": "Astral Radiance",
    "radiance": "Astral Radiance",
    # Pokemon Go
    "pokemon go": "Pokémon GO",
    "pokémon go": "Pokémon GO",
    "pgo": "Pokémon GO",
    "swsh11": "Pokémon GO",
    "pokemon go set": "Pokémon GO",
    # Lost Origin
    "lost origin": "Lost Origin",
    "swsh12": "Lost Origin",
    "lost": "Lost Origin",
    "origin": "Lost Origin",
    # Silver Tempest
    "silver tempest": "Silver Tempest",
    "swsh13": "Silver Tempest",
    "silver": "Silver Tempest",
    "tempest": "Silver Tempest",
    # SWORD & SHIELD SUBSET/SPECIAL SETS
    # Champion's Path
    "champions path": "Champion's Path",
    "champion's path": "Champion's Path",
    "champions": "Champion's Path",
    "champs path": "Champion's Path",
    "cp": "Champion's Path",
    # Shining Fates
    "shining fates": "Shining Fates",
    "shining": "Shining Fates",
    "fates": "Shining Fates",
    "sf": "Shining Fates",
    # Crown Zenith
    "crown zenith": "Crown Zenith",
    "crown": "Crown Zenith",
    "zenith": "Crown Zenith",
    "galarian gallery": "Crown Zenith",
    "cz": "Crown Zenith",
    # Celebrations
    "celebrations": "Celebrations",
    "celebration": "Celebrations",
    "25th anniversary": "Celebrations",
    "25th": "Celebrations",
    # Scarlet & Violet Base Set
    "scarlet violet": "Scarlet & Violet Base",
    "scarlet violet base": "Scarlet & Violet Base",
    "scarlet and violet": "Scarlet & Violet Base",
    "scarlet and violet base": "Scarlet & Violet Base",
    "scarlet & violet": "Scarlet & Violet Base",
    "scarlet & violet base": "Scarlet & Violet Base",
    "sv1": "Scarlet & Violet Base",
    "sv01": "Scarlet & Violet Base",
    "sv base": "Scarlet & Violet Base",
    "base scarlet violet": "Scarlet & Violet Base",
    # Scarlet & Violet Promo
    "scarlet violet promo": "Scarlet & Violet Promo",
    "scarlet violet promo": "Scarlet & Violet Promo",
    "scarlet and violet promo": "Scarlet & Violet Promo",
    "scarlet and violet promo": "Scarlet & Violet Promo",
    "scarlet & violet promo": "Scarlet & Violet Promo",
    "scarlet & violet promo": "Scarlet & Violet Promo",
    "svp": "Scarlet & Violet Promo",
    # Paldea Evolved
    "paldea evolved": "Paldea Evolved",
    "sv2": "Paldea Evolved",
    "sv02": "Paldea Evolved",
    "paldea": "Paldea Evolved",
    "evolved": "Paldea Evolved",
    # Obsidian Flames
    "obsidian flames": "Obsidian Flames",
    "sv3": "Obsidian Flames",
    "sv03": "Obsidian Flames",
    "obsidian": "Obsidian Flames",
    "flames": "Obsidian Flames",
    "obf": "Obsidian Flames",
    # Paradox Rift
    "paradox rift": "Paradox Rift",
    "sv4": "Paradox Rift",
    "sv04": "Paradox Rift",
    "paradox": "Paradox Rift",
    "rift": "Paradox Rift",
    # Paldean Fates
    "paldean fates": "Paldean Fates",
    "paldean": "Paldean Fates",
    "sv4.5": "Paldean Fates",
    "sv45": "Paldean Fates",
    # Temporal Forces
    "temporal forces": "Temporal Forces",
    "sv5": "Temporal Forces",
    "sv05": "Temporal Forces",
    "temporal": "Temporal Forces",
    "forces": "Temporal Forces",
    # Twilight Masquerade
    "twilight masquerade": "Twilight Masquerade",
    "sv6": "Twilight Masquerade",
    "sv06": "Twilight Masquerade",
    "twilight": "Twilight Masquerade",
    "masquerade": "Twilight Masquerade",
    # Shrouded Fable
    "shrouded fable": "Shrouded Fable",
    "sv7": "Shrouded Fable",
    "sv07": "Shrouded Fable",
    "shrouded": "Shrouded Fable",
    "fable": "Shrouded Fable",
    # Stellar Crown
    "stellar crown": "Stellar Crown",
    "sv8": "Stellar Crown",
    "sv08": "Stellar Crown",
    "stellar": "Stellar Crown",
    "crown": "Stellar Crown",
    # Surging Sparks
    "surging sparks": "Surging Sparks",
    "sv9": "Surging Sparks",
    "sv09": "Surging Sparks",
    "surging": "Surging Sparks",
    "sparks": "Surging Sparks",
    # Journey Together
    "journey together": "Journey Together",
    "sv10": "Journey Together",
    "journey": "Journey Together",
    "together": "Journey Together",
    # Destined Rivals
    "destined rivals": "Destined Rivals",
    "sv11": "Destined Rivals",
    "destined": "Destined Rivals",
    "rivals": "Destined Rivals",
    # SCARLET & VIOLET SUBSET/SPECIAL SETS
    # Pokemon 151
    "pokemon 151": "Pokémon 151",
    "pokémon 151": "Pokémon 151",
    "151": "Pokémon 151",
    "sv3.5": "Pokémon 151",
    "sv35": "Pokémon 151",
    # Prismatic Evolutions
    "prismatic evolutions": "Prismatic Evolutions",
    "prismatic": "Prismatic Evolutions",
    "evolutions": "Prismatic Evolutions",
    "prismatic evo": "Prismatic Evolutions",
}
